### PR TITLE
GH-139 enhancements to IDTagger

### PR DESCRIPTION
**Pull request by npeltier**
- make it a service with ability to tag a resource from outside (just in case some service would help tagging more), and ability to fetch an ID using override, current computed id, and a volatile fallback in case,
- that compute id method also generates prefix depending of the 'reference' component context, sets by default to AEM default XF component,
- make almost all sub features optional: rewrite of component hash across page copies, tag on modification, tag on publication, to allow IDTagger in case we want same IDs across MSM, as well as to have IDTagger working on publish without writing anything

### CODE REVIEW

**Comment by janaki-r-bhagwath** [comment]
While with the new code changes, I understand the - `tagOnModification` and `tagOnPublish` are made configurable.  How would we able to have the same id across MSM for a particular component? 
(Maybe we can have an internal discussion on this one - How important it is to us to have HTML id being same (unless authored) across MSM or if we can ignore this requirement)

The current page and resource paths include the locale. 
And hence if we select `tagOnModification` or `tagOnPublish` - in either case, the English page and French page components will get different ids - since page id check determines them different. 

And we would likely want to enable both on author-instance - when authors copy components around on the same page, we want different ids and if some component is missing an id we want the id generated upon publish. 
 
And if we don't select `tagOnModification` or `tagOnPublish`, then we don't get the IDTagger feature.

**Comment by janaki-r-bhagwath** [comment]
Thanks @npeltier for pointing me to `shouldRewriteComponentHash` flag. Missed that. 

Although I still see potential when the ID may change across MSM - that is when the English and French page both don't have component ids originally and are published, which is the case for existing content. 

So, I think we would need to discuss internally, if we at all care deeply about ID same across locales unless authored. Since IDTagger makes the id repository unique which also makes sense.

**Comment by npeltier** [comment]
@janaki-r-bhagwath while i agree with your statement, "future" components, generated in source locale will have an ID that will be persisted across locales, and that is what matters imo. I agree that it's not 100% proof, and especially things without ID getting published (you need to publish *after* your rollout for you scenario ;-) ) will get different IDs.

**Comment by janaki-r-bhagwath** [comment]
Yes. So for existing content today, we will be likely faced with IDs being different across locales since the only time the IDs would get generated would be during publish and might lead to an inconsistent behavior. 

For future components as well, if component is copied in crx/de and then rolled out and published. We would have different IDs across locales. So I'd still think we might need to just have an internal discussion and if we can get rid of the requirement of same ID across locales - we'd have a consistent repo for both existing and new content.

**Pull request merged**
